### ISSUE TITLE
CRIAR LAYOUT DE PÁGINA INICIAL

### ISSUE THREAD

**Issue by DerickCarvalho** [DerickCarvalho/SiteTHEG#2]
CRIAÇÃO DE PROTÓTIPO PARA ORIENTAÇÃO DE FRONT-END DA PÁGINA INICIAL.

**Comment by ehls01** [comment]
Design da página inicial:

https://www.figma.com/file/i76LpCqRsnBz5JYuAxjKId/Untitled?type=design&node-id=0%3A1&mode=design&t=hdKMD4IR7cXkvr0f-1



![Screenshot_1](https://github.com/DerickCarvalho/SiteTHEG/assets/130502704/d82563b9-3ed2-46d1-880a-2699df0a54c0)


Iframe da tela de página inicial:

<iframe style="border: 1px solid rgba(0, 0, 0, 0.1);" width="800" height="450" src="https://www.figma.com/embed?embed_host=share&url=https%3A%2F%2Fwww.figma.com%2Ffile%2Fi76LpCqRsnBz5JYuAxjKId%2FUntitled%3Ftype%3Ddesign%26node-id%3D0%253A1%26mode%3Ddesign%26t%3DhdKMD4IR7cXkvr0f-1" allowfullscreen></iframe>
