### ISSUE TITLE
CRIAÇÃO DE LOGO WIDESCREEN BASEADA NA LOGO DO THEG

### ISSUE THREAD

**Issue by DerickCarvalho** [DerickCarvalho/SiteTHEG#3]
CRIAÇÃO DE LOGO WIDESCREEN PARA PÁGINA INICIAL;

USAR ARTES DA PASTA DO DRIVE.

**Comment by joaonetovhc** [comment]
feito!
https://drive.google.com/drive/folders/1CLjpXT1zljJQo_JjEZoWM0ONG_tyu2tW
