### ISSUE TITLE
Criação de tela de visualizar perfil

### ISSUE THREAD

**Issue by DerickCarvalho** [DerickCarvalho/SiteTHEG#6]
Criar tela de visualização de perfil de usuário (tela que abrirá quando o usuário clicar em sua foto no canto superior direito).

Inputs para:

- Editar foto de perfil (Passando URL Image);
- Editar nome de exibição;
- Botão de logOut;
- Botão de Registrar PC;

**Comment by joaonetovhc** [comment]
Finalizado!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
https://github.com/DerickCarvalho/SiteTHEG/pull/8
